trigger:
- master

pool:
  MyPool

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mv /Users/hosako/Desktop/temp/jars/abbot-1.4.0.jar.moved /Users/hosako/Desktop/temp/jars/abbot-1.4.0.jar
      ln -sfh /Users/hosako/Desktop/temp/jars/jakarta.annotation-api-1.3.5.jar ./jakarta.annotation-api-1.3.5.jar
      ln -sfh /Users/hosako/Desktop/temp/jars/abbot-1.4.0.jar ./abbot-1.4.0.jar
      mv /Users/hosako/Desktop/temp/jars/abbot-1.4.0.jar /Users/hosako/Desktop/temp/jars/abbot-1.4.0.jar.moved
- task: NexusIqPipelineTask@2
  inputs:
    nexusIqService: 'local_iq'
    applicationId: 'sandbox-application'
    stage: 'stage-release'
    scanTargets: '**/*.jar, **/*.war, **/*.ear, **/*.zip, **/*.tar.gz, **/*.txt'
    ignoreSystemError: true
    ignoreScanningError: true
    enableDebugLogging: true
