trigger:
- master

pool:
  MyPool

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ln -sfh /tmp/requirements.txt ./requirements.txt
      cp -f -v /Users/hosako/Desktop/temp/jars/jakarta.annotation-api-similar-1.3.5.jar ./jakarta.annotation-api-similar-1.3.5.jar
      ln -sfh /Users/hosako/Desktop/temp/jars/jakarta.annotation-api-1.3.5.jar ./jakarta.annotation-api-1.3.5.jar
- task: NexusIqPipelineTask@2
  inputs:
    nexusIqService: 'local_iq'
    applicationId: 'sandbox-application'
    scanTargets: '**/*'
    stage: 'stage'
    enableDebugLogging: true
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
