# Maven

trigger:
- master

pool:
  MyPool

steps:
- task: Maven@4
  inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx2048m'
      javaHomeOption: 'JDKVersion' 
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ln -sfh /tmp/requirements.txt ./requirements.txt
- task: NexusIqPipelineTask@2
  inputs:
    nexusIqService: 'local_iq'
    applicationId: 'sandbox-application'
    stage: 'stage'
    enableDebugLogging: true
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
