# Test for #103486
trigger:
- master

pool:
  MyPool

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "{" > package.json
      ln -sfh /Users/hosako/Desktop/temp/jars/abbot-1.4.0.jar ./abbot-1.4.0.jar
- task: NexusIqPipelineTask@2
  inputs:
    nexusIqService: 'local_iq'
    applicationId: 'sandbox-application'
    stage: 'stage-release'
    scanTargets: '**/*.jar, **/*.war, **/*.ear, **/*.zip, **/*.tar.gz, **/*.txt, **/*.json, !**/package.json'
    ignoreSystemError: true
    ignoreScanningError: true
    enableDebugLogging: true
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      find . -name evaluationResult.json | xargs cat
